### PR TITLE
Iam role option

### PR DESCRIPTION
**Pull request by vitorarins**
This was sitting here for a while, I have no idea why it wasn't merged.

### CODE REVIEW

**Review by lborguetti — APPROVED** [review]
LGTM!

**Comment by guilherme-santos** [comment]
Hey, I think it was not merged because the IAM option doesn't have on lib that we are using, I think I created a branch with this change but I'm not sure, I can check later!

**Comment by guilherme-santos** [comment]
I think I created a PR to goamz and they haven't accepted yet!

**Comment by vitorarins** [comment]
@guilherme-santos that's weird. I just tested the branch and it created the machine normally with the IAM role.

**Pull request merged**
